apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: jv4ygam5svaeq.azurecr.io/tyler/myfirstapp:$BUILD_NUMBER
        ports:
        - containerPort: 80